### ISSUE TITLE
Long loading times for large projects

### ISSUE THREAD

**Issue by igor-budi** [j-roskopf/ModuleMakerPlugin#37]
I am using this plugin on a large project and it takes tens of seconds (40+ is the worst I got) to load the file picker.

From playing with the code, it looks like this part is what causing the holdup and blocking the plugin window
```kotlin
class FileTree(path: String) : JTree(scan(File(path))) {
    companion object {
        private fun scan(node: File): MutableTreeNode {
            val ret = DefaultMutableTreeNode(node.name)
            if (node.isDirectory) for (child in node.listFiles()!!) ret.add(scan(child))
            return ret
        }
    }
}
```

Personally, I have no experience with writing UI for plugins so I can't solve this myself.

I believe the best approach here is to lazy load the folders, one level at a time, similar to what jetbrains is doing in their file picker

**Comment by j-roskopf** [comment]
hey! I think that totally makes sense. I wasn't able to repro any super long waiting times on the few bigger open source projects I tested like tivi / firefox, but I'm also guessing it's very project + computer dependent!

regardless, I have created a release version 1.1.12 which significantly overhauls the file explorer.

Would you be willing to install the zip manually and help verify if the issue seems to be addressed for you? Totally understandable if not, but please let me know either way so I can upload the plugin to a beta channel for some feedback before a wider release.

The release can be found here https://github.com/j-roskopf/ModuleMakerPlugin/releases/tag/release%2F1.1.12 and instructions to install from disk can be found here https://github.com/j-roskopf/ModuleMakerPlugin#installation

Thank you for reporting!

**Comment by igor-budi** [comment]
@j-roskopf yes! 
1.1.12 installed locally and it was loaded immediately

**Comment by j-roskopf** [comment]
awesome! thanks for confirming. i'll upload 1.0.12 for a wider release.
